version: '3.8'

services:
  api:
    image: fline/api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: fline-api
    ports:
      - '3333:3333'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4-alpine
    container_name: fline-postgres
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - ./apps/api/data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    container_name: fline-adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    env_file:
      - .env.local
